# Generated by Django 2.2.2 on 2019-06-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ateapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Offres',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='tutorial_content',
            new_name='offre_content',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='tutorial_published',
            new_name='offre_published',
        ),
        migrations.RenameField(
            model_name='offres',
            old_name='tutorial_title',
            new_name='offre_title',
        ),
    ]
